# Cloudflare Pages configuration
name = "getlifesorted"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "npm run build"
output_dir = "dist"
base_dir = ""

# Environment variables
[vars]
NODE_VERSION = "18"

# Production environment
[env.production]
# Add production-specific variables here if needed
# MY_VAR = "production-value"

# Preview environment (for pull requests)
[env.preview]
# Add preview-specific variables here if needed
# MY_VAR = "preview-value"

# Routes configuration
[routes]
# Force HTTPS
pattern = "http://*"
script = """
  addEventListener('fetch', event => {
    event.respondWith(
      Response.redirect('https://' + event.request.url.slice(7), 301)
    )
  })
"""

# Cache configuration
# Using array of tables for multiple cache rules
[[cache]]
pattern = "/assets/*"
ttl = 31536000

[[cache]]
pattern = "/images/*"
ttl = 604800

[[cache]]
pattern = "/*.html"
ttl = 0
