# Cloudflare Pages configuration for Astro
name = "getlifesorted"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Build configuration
[build]
command = "npm run build"

# Assets configuration
[assets]
directory = "./dist"

# Environment variables
[env.production]
vars = { NODE_VERSION = "22" }

[env.preview]
vars = { NODE_VERSION = "22" }
